title: "My Blog"
description: "Tech notes, networking, and personal learning"
url: "https://andreansxtech.github.io"
baseurl: "/Blog" 

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

author:
  name: "Andreansx"